### ISSUE TITLE
Basic set up issues

### ISSUE THREAD

**Issue by ghost** [ericdfields/Jekyll-Dribbble-Set-Tag#1]
I have changed the _config file and added in the relevant details. I then add the {% dribble_set user:joshua_hornby %} in the index.html file where i want to shots to be shown. When i run Jekyll and load the site up all the liquid tags are being shown, so in other words they aren't working. The error message i get is Liquid Exception: Unknown tag 'dribble_set' in index.html.

Im new to all this so i might be missing something very obvious

**Comment by ericdfields** [comment]
Right away I found a problem: change dribble_set to dribbble_set :) … damn autocorrect!

Doing a quick setup to make sure the basics work as intended.

**Comment by ghost** [comment]
I've changed that! I should of really found that been staring at this screen too long ;) But still same error : Liquid Exception: Unknown tag 'dribbble_set' in index.html

**Comment by ericdfields** [comment]
That means its not reading the plugin, which should be in _plugins as dribbble_set.rb.

**Comment by ericdfields** [comment]
I'm getting a different error when i try to use the plugin in its most basic state. Jekyll errors are notoriously terse and unhelpful. I really can't debug this until tonight after work :(

**Comment by ghost** [comment]
Are you getting this error Liquid Exception: undefined method `[]' for nil:NilClass in index.html this is what i just got. I really appreciate the time in looking at this for me.

**Comment by ericdfields** [comment]
Yup. Actually just figured it out. Posting a fix…

**Comment by ghost** [comment]
Brilliant! :)

**Comment by ericdfields** [comment]
Pull the latest. Inline config isn't working for some reason I can't debug right now, but it'll read from the Jekyll config and let you compile at least. Thanks for giving the plugin a shot!
